export let pathsContainerEl = null as unknown as HTMLElement
export let addPathBtnEl = null as unknown as HTMLElement
export let playlistsContainerEl = null as unknown as HTMLElement
export let addPlaylistBtnEl = null as unknown as HTMLElement
export let toastEl = null as unknown as HTMLElement
export let playlistCoverEl = null as unknown as HTMLImageElement
export let playlistTitleEl = null as HTMLElement
export let playlistDescriptionEl = null as HTMLElement
export let playButtonEl = null as HTMLButtonElement
export let searchInputEl = null as HTMLInputElement
export let searchButtonEl = null as HTMLElement
export let bottomBarTextEl = null as HTMLElement
export let queueToggleButtonEl = null as HTMLButtonElement
export let showMissingSongsToggleButtonEl = null as HTMLButtonElement
export let queuePopupEl = null as HTMLElement
export let fixedPlaylistEl = null as HTMLElement
export let loadingOverlayEl = null as HTMLElement
export let playlistModalEl = null as HTMLElement
export let playlistNameInputEl = null as HTMLInputElement
export let playlistDescriptionInputEl = null as HTMLTextAreaElement
export let playlistCoverInputEl = null as HTMLInputElement
export let playlistCoverPreviewEl = null as HTMLImageElement
export let playlistModalTitleEl = null as HTMLElement
export let playlistModalSaveButtonEl = null as HTMLButtonElement
export let playlistModalDeleteButtonEl = null as HTMLButtonElement
export let playlistEditButtonEl = null as HTMLButtonElement
export let playlistModalAddSongsButtonEl = null as HTMLButtonElement
export let playlistAddSongsSectionEl = null as HTMLElement
export let playlistAddSongsTitleEl = null as HTMLElement
export let playlistAddSongTitleInputEl = null as HTMLInputElement
export let playlistAddSongComposerInputEl = null as HTMLInputElement
export let playlistAddSongAlbumInputEl = null as HTMLInputElement
export let playlistAddSongSubmitButtonEl = null as HTMLButtonElement
export let playlistAddSongsBackButtonEl = null as HTMLButtonElement
export let playlistAddedSongsCountEl = null as HTMLElement
export let contextMenuEl = null as HTMLElement
export let shuffleButtonEl = null as HTMLButtonElement
export let prevButtonEl = null as HTMLButtonElement
export let playToggleButtonEl = null as HTMLButtonElement
export let nextButtonEl = null as HTMLButtonElement
export let repeatButtonEl = null as HTMLButtonElement
export let volumeSliderEl = null as HTMLInputElement
export let trackTitleEl = null as HTMLElement
export let trackPerformerEl = null as HTMLElement
export let timeStartEl = null as HTMLElement
export let timeEndEl = null as HTMLElement
export let timeBarTrackEl = null as HTMLElement
export let timeBarFillEl = null as HTMLElement
export let timeBarThumbEl = null as HTMLElement

export function bindDomElements() {
  pathsContainerEl = document.querySelector('.paths-container')!
  addPathBtnEl = document.querySelector('.add-path-btn')!
  playlistsContainerEl = document.querySelector('.playlists-container')!
  addPlaylistBtnEl = document.querySelector('.add-playlist-btn')!
  toastEl = document.querySelector('.toast')!
  loadingOverlayEl = document.querySelector('.sync-overlay')!
  playlistModalEl = document.querySelector('.playlist-modal') as HTMLElement
  playlistModalTitleEl = document.querySelector('.playlist-modal-title') as HTMLElement
  playlistNameInputEl = document.querySelector('.playlist-name-input') as HTMLInputElement
  playlistDescriptionInputEl = document.querySelector('.playlist-description-input') as HTMLTextAreaElement
  playlistCoverInputEl = document.querySelector('.playlist-cover-input') as HTMLInputElement
  playlistCoverPreviewEl = document.querySelector('.playlist-cover-preview') as HTMLImageElement
  playlistModalSaveButtonEl = document.querySelector('.playlist-modal-save') as HTMLButtonElement
  playlistModalDeleteButtonEl = document.querySelector('.playlist-modal-delete') as HTMLButtonElement
  playlistModalAddSongsButtonEl = document.querySelector('.playlist-modal-add-songs-button') as HTMLButtonElement
  playlistAddSongsSectionEl = document.querySelector('.playlist-add-songs-section') as HTMLElement
  playlistAddSongsTitleEl = document.querySelector('.playlist-add-songs-title') as HTMLElement
  playlistAddSongTitleInputEl = document.querySelector('.playlist-add-song-title') as HTMLInputElement
  playlistAddSongComposerInputEl = document.querySelector('.playlist-add-song-composer') as HTMLInputElement
  playlistAddSongAlbumInputEl = document.querySelector('.playlist-add-song-album') as HTMLInputElement
  playlistAddSongSubmitButtonEl = document.querySelector('.playlist-add-song-submit') as HTMLButtonElement
  playlistAddSongsBackButtonEl = document.querySelector('.playlist-add-songs-back') as HTMLButtonElement
  playlistAddedSongsCountEl = document.querySelector('.playlist-added-songs-count') as HTMLElement
  playlistCoverEl = document.querySelector('.playlist-cover') as HTMLImageElement
  playlistTitleEl = document.querySelector('.playlist-title')!
  playlistDescriptionEl = document.querySelector('.playlist-description')!
  bottomBarTextEl = document.querySelector('.bottom-bar-content')!
  queueToggleButtonEl = document.querySelector('.queue-toggle-button') as HTMLButtonElement
  showMissingSongsToggleButtonEl = document.querySelector('.show-missing-toggle-button') as HTMLButtonElement
  queuePopupEl = document.querySelector('.queue-popup') as HTMLElement
  contextMenuEl = document.querySelector('.context-menu') as HTMLElement
  searchInputEl = document.querySelector('.playlist-search-input') as HTMLInputElement
  searchButtonEl = document.querySelector('.playlist-search-button') as HTMLElement
  playButtonEl = document.querySelector('.playlist-play-button') as HTMLButtonElement
  playlistEditButtonEl = document.querySelector('.playlist-edit-button') as HTMLButtonElement
  fixedPlaylistEl = document.querySelector('.fixed-playlist') as HTMLElement
  shuffleButtonEl = document.querySelector('.shuffle-button') as HTMLButtonElement
  prevButtonEl = document.querySelector('.prev-button') as HTMLButtonElement
  playToggleButtonEl = document.querySelector('.play-toggle-button') as HTMLButtonElement
  nextButtonEl = document.querySelector('.next-button') as HTMLButtonElement
  repeatButtonEl = document.querySelector('.repeat-button') as HTMLButtonElement
  volumeSliderEl = document.querySelector('.volume-slider') as HTMLInputElement
  trackTitleEl = document.querySelector('.track-title') as HTMLElement
  trackPerformerEl = document.querySelector('.track-performer') as HTMLElement
  timeStartEl = document.querySelector('.time-start') as HTMLElement
  timeEndEl = document.querySelector('.time-end') as HTMLElement
  timeBarTrackEl = document.querySelector('.time-bar-track') as HTMLElement
  timeBarFillEl = document.querySelector('.time-bar-fill') as HTMLElement
  timeBarThumbEl = document.querySelector('.time-bar-thumb') as HTMLElement
}
